---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: &app vault-backend
spec:
  provider:
    vault:
      server: "${VAULT_SERVER}"
      path: "kv"
      version: "v2"
      auth:
        # VaultUserPass authenticates with Vault using the UserPass auth mechanism
        # https://www.vaultproject.io/docs/auth/userpass
        userPass:
          # Path where the UserPass authentication backend is mounted
          path: "userpass"
          username: "${VAULT_USER}"
          secretRef:
            name: "vault-cluster-creds"
            key: "password"
            namespace: external-secrets
