apiVersion: v1
kind: Secret
metadata:
    name: ns-external-secrets-secret
stringData:
    #ENC[AES256_GCM,data:feGa24XOpV7PZb8Lhc8PglwZsl/OQuEx5HVHbj9rJafkk3WQeZu7fyOyOjc9Ed1jfj43,iv:tdKw8hUoeJe5HpsiKxoRMaQeQqagnuyuD7238Ibx+Wk=,tag:VbVfNMWSFP3wNBwRBbuG7w==,type:comment]
    VAULT_SERVER: ENC[AES256_GCM,data:CraI6mpTOto+uM6+A1sD+AcJ304JToVvGMD+,iv:/wlatpxhOyq756tnjHoN+hRG1eRUurWmH+4AMl6drOE=,tag:KDJZfrAZgw2I6+fE7AgHmA==,type:str]
    VAULT_USER: ENC[AES256_GCM,data:GbSQkSMujw==,iv:sDAM+bHwK5EVcURFv+T9wVa7EsyBpb0HFqu2dRShEhw=,tag:4lbGMva9cadBrw2WH/W6oQ==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T22:07:14Z"
    mac: ENC[AES256_GCM,data:1Ts1lKmxfVlNlrDCuMNmoc1asjmW24nPgW7Bp/+3SVEmI/oxEkRhz0TByBhpNbrJQBjU2t71/VYMNjmDmWFtK3QaO76Z3Z/k3lirtWEvAhnaGOFI25BToOwBU3Sl0BMTgD7TPwMv4aGCYCgPAg5tI6qqzhmTPoV0/sriLa7BwoA=,iv:R7vt+6BEoDwc+PLFbFOTRhByruphCtzqsZ2YW1AcPFM=,tag:8Th6ETzo4ubvT7xuKfDN6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
