---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  CLUSTER_TIMEZONE: "Europe/Berlin"
  CLUSTER: core
  DOMAIN: core.lokis-casa.internal
  SERVICE_LB_RANGE: 10.0.69.50-10.0.69.99
  # range lan: 192.168.0.171-192.168.0.180
  LB_V4_K8SGATEWAY: 10.0.69.50
  #CLUSTER_LB_SMTP_RELAY: 192.168.169.102
  LB_V4_NGINX_INTERNAL: 10.0.69.50
  LB_SERVICE_INTERFACE: services
