---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
components:
  - ../../../components/common
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  - ../../../vars/main/ns/external-secrets-secrets.sops.yaml
  - ./external-secrets.yaml
  - ./external-secrets-pdb.yaml

