---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
components:
  - ../../../components/common
  - ../../../vars/core
resources:
  - ./cert-manager.yaml
  - ./issuer.yaml
  - ./issuer-internal.yaml
  #- ./issuer/selfsign/ks.yaml
