---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
data:
  allow-share-default: 'true'
  allow-share-services: 'true'
  interface-global: eth0
  interface-services: services
  range-default: 10.0.60.50-10.0.60.99
  range-services: 10.0.69.50-10.0.69.99
