---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/requirements.json
# Ansible galaxy requirements
roles:
  - name: lablabs.rke2
    src: https://github.com/lablabs/ansible-role-rke2
    version: 1.50.1
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: community.general
    version: 12.3.0
    # https://github.com/ansible-collections/community.sops
  - name: community.sops
    version: 2.2.7
  - name: maxhoesel.pterodactyl
    version: 5.0.0
    # https://github.com/maxhoesel-ansible/ansible-collection-pterodactyl/tree/main
