---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  CLUSTER_TIMEZONE: "Europe/Berlin"
  CLUSTER: casa
  SHARED_MEDIA_PATH: "/opt/homelab/media"
  SHARED_DATA_PATH: "/opt/homelab/data"
  SHARED_DATAPACK_PATH: "/opt/homelab/shareddata"

  SCFASTPATH: /opt/homelab/k3sfdiscs
  SCSTANDARDPATH: /opt/homelab/k3smdiscs
  #SHARED_MDISC_PATH: "/opt/homelab/k3smdiscs"
  #SHARED_FDISC_PATH: "/opt/homelab/k3sfdiscs"
  DOMAIN: casa.lokis-casa.internal
  # range lan: 192.168.0.222-192.168.0.240
  #SERVICE_LB_RANGE: 192.168.0.222-192.168.0.240
  # SERVICE_LB_RANGE: 10.0.69.50-10.0.69.99
  # range iot: 192.168.188.235-192.168.188.245
  #SERVICE_LB_RANGE_IOT: 192.168.188.235-192.168.188.245

  LB_SERVICE_INTERFACE: services
  LB_INTERNAL_INTERFACE: eth0
  #CLUSTER_LB_K8SGATEWAY: 192.168.0.223
  #CLUSTER_LB_K8SGATEWAY_IOT: 192.168.188.236
  ##CLUSTER_LB_SMTP_RELAY: 192.168.169.102
  #CLUSTER_LB_NGINX_INTERNAL: 192.168.0.222
  #CLUSTER_LB_NGINX_IOT: 192.168.188.235
  #CLUSTER_LB_SMB_IOT: 192.168.188.235

  LB_V4_K8S_GATEWAY: 192.168.0.223
  LB_V4_K8S_GATEWAY_IOT: 192.168.188.236
  LB_V4_NGINX_INTERNAL: 192.168.0.222
  LB_V4_NGINX_IOT: 192.168.188.235
  LB_V4_NGINX_BASE_IOT: 192.168.188.237
  LB_V4_NGINX_DEV_IOT: 192.168.188.238
  LB_V4_SMB_IOT: 192.168.188.235
  LB_V4_NUT_IOT: 192.168.188.235

  LB_V4_GATEWAY_INTERNAL: 192.168.0.224
  LB_V4_GATEWAY_MAIN: 192.168.188.239
  LB_V4_GATEWAY_BASE: 192.168.188.240
  LB_V4_GATEWAY_DEV: 192.168.188.241
  LB_V4_GATEWAY_L4: 192.168.188.242
  LB_V4_MARIADB: 192.168.0.225
  LB_V4_SHARED: 192.168.188.243

  #LB_V4_SMTP_RELAY: 192.168.169.102
  #LB_V4_LLDAP
  #LB_V4_GO2RTC
  #LB_V4_JELLYFIN
  LB_V4_JELLIFIN_IOT: 192.168.188.235
  SVC_KUBE_DNS_V4: "10.43.0.10"

  # Network CIDR used for pod IPs
  NETWORK_K8S_CLUSTER_CIDR: "10.42.0.0/16"
  # Network CIDR used for service IPs
  NETWORK_K8S_SERVICE_CIDR: "10.43.0.0/16"
  LOCAL_CIDR_1: "192.168.0.0/24"
  LOCAL_CIDR_2: "192.168.188.0/24"

  LOCAL_CIDR_2_GATEWAY: 192.168.188.1
