apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:E0d/CV7PxsJaggTd+WHsOzCuJt/JsTw=,iv:MNTNNgR6UzbQQdshNUect/iPAPnEAbAyrwWU2TOu9tg=,tag:OMesoC5H7aKcobSTkHu5fQ==,type:str]
    SECRET_MAIN_DOMAIN_NAME: ENC[AES256_GCM,data:R+fF31laUCyiGzjAMReJ,iv:b7Pg9eMlt4nM1xAuaaS9c7B9UIW2VS3motZodNp74cE=,tag:tmNQBAmh41rDi+9Do9AaZA==,type:str]
    SECRET_SSO_DOMAIN_NAME: ENC[AES256_GCM,data:UIxsi58rD5ewLRcGtxx3Lh4ANxQc,iv:jmc0zPYnoV21sKX2JYSzLVNNRol974BPscyB6gNw2eE=,tag:+uMHKruWl8+mKgguMVOA7w==,type:str]
    SECRET_DOMAIN_NAME: ENC[AES256_GCM,data:R1gRQjGXJhO4IXt5Og==,iv:G11UMCdsozBWahSOEyoDg4cd9mK3bgzrK7q6Semd8ms=,tag:50JBI+gaxPvjJxl2sE3afg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:fuaUmRAfuP0XAQ==,iv:/BRT28bLQeThbc3RvlOew+GR2HlJfHCo3L1SHn95T68=,tag:v5QnKXraM653qboIef04pw==,type:str]
    SECRET_SSO_DOMAIN: ENC[AES256_GCM,data:lTvdRWedQUF9nyYW0A==,iv:92vQdxLr+Y9hfwRDnrScshN/QwT051h3L1zAG5dJubI=,tag:Q0j3K2E1lfmxdwPKECt8CQ==,type:str]
    SECRET_SSO_DOMAIN_2: ENC[AES256_GCM,data:iFy9YJikRU+BhO0=,iv:WX7m++2XUMx3kGAOkApnF4MWBlEuIMHO+/FYEOhoWd4=,tag:EniYa7mOL5IMHUCJUHQC1w==,type:str]
    SECRET_N8NWEBHOOKS_DOMAIN: ENC[AES256_GCM,data:DJDa2KtCouD/e4rffZo6KT/sQgo5xQ==,iv:eYXC1oRbbDRbAI90Tqv7sCKXoGF0hFf92J5PNMvedYU=,tag:w/bDSi/erbqftadeQbFjPw==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:t/1r8//idWs=,iv:3Ubbq5woCV4AVR1RRM9YAiG86wLbajDyDEE+WhKCXfg=,tag:wOEy+dDuSwL+sm5AkHgp0Q==,type:str]
    SECRET_GAME_DOMAIN: ENC[AES256_GCM,data:QwWWpY6JmVA=,iv:X2ml/wZL4l/6kC44ZYnjgzLt9A9wLoXuAn+aJl2e5MA=,tag:bn1333yOHhBIwD8wKYpNEQ==,type:str]
    SECRET_PM1_DOMAIN: ENC[AES256_GCM,data:srLosrbx/C94p5a5,iv:aWZsC7KEIGgW5VauVMmH+f0P+fwSPGhR6PAB4VPC0As=,tag:mV5enYwtJwp+JzT1hHhHaQ==,type:str]
    SECRET_PM2_DOMAIN: ENC[AES256_GCM,data:jhK/T112X2IouVrYUr0=,iv:u/6YnCXBnoYis8zentedVtHrlsbI330V5tU3q83jp7U=,tag:TAXS3gstCD9sDXC5bPOjbw==,type:str]
    FLUX_WEBHOOK_EXTERNAL: ENC[AES256_GCM,data:07QmCTUJoC+/5ANG+UbegML8aSCOc2JrqE8=,iv:hi+SXYUlMWjujyHr4NAVm2eLWtxvDJHOtbyKle4lMj0=,tag:L/Bl3FVsl7Fd1r4i49aH4Q==,type:str]
    FLUX_WEBHOOK_CORE_EXTERNAL: ENC[AES256_GCM,data:05/mLi/h1Gp4zN+8Ek3aS6T+FTQhYlzeFBU=,iv:9f+EHtM27s5GMFzXHTIbaSJ8Fqtzt7LJ8cW/9eS/KEY=,tag:KOKnYKi3NPZlGyvX4yjGFQ==,type:str]
    SMTP_RELAY_HOST: ENC[AES256_GCM,data:eo8BCVzZZf+JHpDdDD4Oar88KAEOfAIBjc1hCsA3vTORzA==,iv:G0T0hrjjaHfpcWZ8gp2GS/YshtW+s2N6bLR+qwmnDKE=,tag:94W8H7WFgsJrS6lseC9CXg==,type:str]
    SECRET_SMTP_FROM_FULL: ENC[AES256_GCM,data:wp83sH57R2VX5QB4TE1d949eMg==,iv:JRgMv2SWY4sxcbFYZzirSeVrEMhpdxAP3k5bU8402Os=,tag:VQ1vYU7rbB81eMBfqSBPsw==,type:str]
    CACHE_DOCKERIO_PREFIX: ENC[AES256_GCM,data:gw6m2mX3Jv2U8Q70sojY2f3ulOZ/Ek57OOhM2mXVF7ox,iv:+swamaUs3Q3110H93WDqZ361PjJTH99K3CUDYQcH7P0=,tag:LDm2zRK9w1YrWmXa/qQ3iw==,type:str]
    CACHE_IMAGES_PREFIX: ENC[AES256_GCM,data:6MRVZbG0pf+r8/GxY2Uj+vtvCHEUI8M=,iv:3yfkfxInWE2Bn6Wzkl9ols1DBz89JnqN2p4P8Z1YpQ4=,tag:Rmqp2l/a3Dph3ZVsnXCDkg==,type:str]
    SECRET_FRITZ_IP: ENC[AES256_GCM,data:tivPwdwmofB1bYSU8g==,iv:r+6R14wT+gT1i/MUkFVnbfwWk+f5f193BKwNr/ENh6s=,tag:QhPARgDxKO7sLy1OJf5Eyw==,type:str]
    SECRET_OPNSENSE_IP: ENC[AES256_GCM,data:dzOWuPeKSaT85ow3NQ==,iv:nD4pjnRDBML0kwPpO5IuOXQ7h0onmi4JRcB3EbIfZGw=,tag:Tehb6xD0FfMQv7wPDmfP5Q==,type:str]
    SECRET_GTW_IP: ENC[AES256_GCM,data:qkhtRrgz8UTvBu3YQw==,iv:4ZRLJ4cTqATrY6FgswtYWf0a9rPJHKhRcRTd1vC2tiE=,tag:TPnDu68tnYhDrG6cGhSBMQ==,type:str]
    SECRET_AI1_IP: ENC[AES256_GCM,data:8U3om0Pq6FJYiQxv,iv:DZwwG8oSUyHV54/m9mI95loz7kAbj6VCBW/eLgb6Dcg=,tag:H7J6jSx+EU2Dx3VPUIslUQ==,type:str]
    SECRET_S3_BACKUP_STORAGE_IP: ENC[AES256_GCM,data:kScsNqUUzEXb1g==,iv:8SarV2LeMF2x0mV6uUiJPdZemii9Lz4FjFGEUa0XxC8=,tag:gi+iulVt4AYBpSa3GUrfNw==,type:str]
    SECRET_S3_BACKUP_STORAGE: ENC[AES256_GCM,data:4tQi/Jj4LKAvBIgpv3Vm9UGGB0I/Rw==,iv:tWbQ4EUbThZWjAxfeOV5J0wCdYFMRh5H2YdOixQNkmM=,tag:nkCm45wZflRufEH1snF7nQ==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:26:28Z"
    mac: ENC[AES256_GCM,data:MTICpayNIbGmUuw4EMY2flqudF1BWVobi4JLkh//j8hZaQNBM4TyFq+yf6ixlucF4bdukG7wAHMu9sEPbKSQ9WlAx65QR4XHJCT8cRDIFSwJh07c0EkhTIbvTdrZzudP9+N8rxx1aiKGUVnPvRHhE6Pv2nMh9oaYG+ZqnW4XIUs=,iv:zzQeQYv+zAil5LMPuTJ0SAWd8JT4x7SqD4ctOpB5Tgs=,tag:Z1AoWBINLx3f/2r/A7QQWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
