apiVersion: v1
kind: Secret
metadata:
    name: ns-security-secret
stringData:
    #ENC[AES256_GCM,data:feGa24XOpV7PZb8Lhc8PglwZsl/OQuEx5HVHbj9rJafkk3WQeZu7fyOyOjc9Ed1jfj43,iv:tdKw8hUoeJe5HpsiKxoRMaQeQqagnuyuD7238Ibx+Wk=,tag:VbVfNMWSFP3wNBwRBbuG7w==,type:comment]
    VAULT_SERVER: ENC[AES256_GCM,data:CraI6mpTOto+uM6+A1sD+AcJ304JToVvGMD+,iv:/wlatpxhOyq756tnjHoN+hRG1eRUurWmH+4AMl6drOE=,tag:KDJZfrAZgw2I6+fE7AgHmA==,type:str]
    VAULT_USER: ENC[AES256_GCM,data:y+mnZWkzMieTDEuF,iv:A+P/EWukrtLsTZTGcRXI28iAN7ftrrez2RjTrPmydYA=,tag:lAOGMKM5p2+vgfdtDl61/Q==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:20:20Z"
    mac: ENC[AES256_GCM,data:0n6tdZmXpmk0Yp3Ms0YRTmtfCN+nh6Od398LdqM/wsRAl4orbCUanDpyw0JT51U2h+oyenmLXvYlczC5Y27M5327Kiq6VxoBw6lME5y2zUx9+Szysmiv62Cj6kOIu7SjAV2kH78il9o3pws0I1WSZ9Y+Nft1kDfr5T8Twes+CSc=,iv:BMVPGia6d61W6OWDng8FT0ljpVwq5xFynrY/MWAJxy0=,tag:8UenGgeVvveOuzxz30/0Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
